# NumPy 

In [2]:
# importação do pacote abaixo com abreviação 
import numpy as np 

# NumPy - criação de matrizes

In [3]:
# Matriz de uma dimensão 
np.array([1,2,3]) 

array([1, 2, 3])

In [4]:
# Matriz bidimensional 
np.array([[1, 2], [3, 4]]) 

array([[1, 2],
       [3, 4]])

In [5]:
# Array 1D de comprimento 3 todos os valores 0
np.zeros(3)

array([0., 0., 0.])

In [6]:
# Matriz 3x4 com todos os valores em 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Matriz 5x5 de 0 com 1 na diagonal (matriz de identidade)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# Matriz de 6 valores divididos uniformemente de 0 a 100
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [9]:
# Matriz de valores de 0 a menos de 10 com a etapa 3 (por exemplo, [0,3,6,9])
np.arange(0,10,3)

array([0, 3, 6, 9])

In [10]:
# Array 2x3 com todos os valores 8
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [11]:
# Matriz 4x4 de flutuadores aleatórios entre 0-1
np.random.rand(4,4)

array([[0.83452104, 0.81979364, 0.36015985, 0.43303911],
       [0.61000359, 0.41863868, 0.30367192, 0.58909765],
       [0.25022262, 0.93297265, 0.23465584, 0.0378262 ],
       [0.27517589, 0.42482127, 0.57885906, 0.19194516]])

In [12]:
# Matriz 4x3 de flutuações aleatórias entre 0-100
np.random.rand(4,3)*100

array([[22.17008449, 41.46018119, 68.85042936],
       [41.94357667, 61.59516478, 30.75219722],
       [17.25902879, 50.07881245, 14.92041767],
       [82.47510576, 79.88747646, 60.62178018]])

In [13]:
# Matriz 2x3 com números inteiros aleatórios entre 0-4
np.random.randint(5,size=(2,3))

array([[0, 3, 4],
       [2, 4, 4]])

# NumPy - remodelando dados

In [14]:
# Cria matriz 2D de 1 a 10 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
# Transforma a matriz de 2D para 1D
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Transpõe arr (linhas tornam-se colunas e vice-versa)
arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [17]:
# Remodela arr para 1 linha e 1 coluna sem alterar os dados
arr.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [18]:
# Matriz 2x3 todos valores 5 atribui arr2
arr2 = np.full((2,3),5)
arr2
# Altera a forma arr2 para 3x3 e preenche novos valores com 0
arr2.resize(3,3)
arr2

array([[5, 5, 5],
       [5, 5, 5],
       [0, 0, 0]])

# NumPy - adicionando e removendo elementos

In [19]:
# Matriz para exemplo
# Cria matriz 4x4 com todos valores 10
arr3 = np.full((4,4),10)
arr3

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [20]:
# Acrescenta valores ao final do arr3 equivalentes a matriz 4x4 com valores 5
values = np.full((4,4),5)
arr4   = np.append(arr3,values)
arr4


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5])

In [21]:
# Exclui linha no índice 3 de arr4 equivalente ao valor 10 na posição 15-16
np.delete(arr4,3,axis=0)


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5])

# NumPy - combinando e dividindo elementos 

In [22]:
# Matrizes para exemplos 
# Cria matriz 4x4 com todos valores 10
arr5 = np.full((4,4),10)
# Cria matriz 4x4 com todos valores 10
arr6 = np.full((4,4),20)

In [23]:
# Adiciona arr6 como linhas ao final de arr5
arr7 = np.concatenate((arr5,arr6),axis=0)
arr7

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [24]:
# Divide o arr7 em 4 sub-matrizes
arr8 = np.split(arr7,4)
arr8

[array([[10, 10, 10, 10],
        [10, 10, 10, 10]]),
 array([[10, 10, 10, 10],
        [10, 10, 10, 10]]),
 array([[20, 20, 20, 20],
        [20, 20, 20, 20]]),
 array([[20, 20, 20, 20],
        [20, 20, 20, 20]])]

In [25]:
# Aplica divisões horizontalmente no 2º índice da matriz arr7
np.hsplit(arr7,2)


[array([[10, 10],
        [10, 10],
        [10, 10],
        [10, 10],
        [20, 20],
        [20, 20],
        [20, 20],
        [20, 20]]),
 array([[10, 10],
        [10, 10],
        [10, 10],
        [10, 10],
        [20, 20],
        [20, 20],
        [20, 20],
        [20, 20]])]

# NumPy - Matemática Básica 

In [26]:
# Matriz de exemplo
arr9 = np.full((2,2),10)
arr9

array([[10, 10],
       [10, 10]])

In [27]:
# Adiciona 1 a cada elemento da matriz
np.add(arr9,1)

array([[11, 11],
       [11, 11]])

In [28]:
# Subtrai 2 de cada elemento da matriz original 
np.subtract(arr9,2)

array([[8, 8],
       [8, 8]])

In [29]:
# Multiplica cada elemento da matriz por 3
np.multiply(arr9,3)    

array([[30, 30],
       [30, 30]])

In [30]:
# Divide cada elemento da matriz por 4 (retorna np.nan para divisão por zero)
np.divide(arr9,4)

array([[2.5, 2.5],
       [2.5, 2.5]])

In [31]:
# Eleva cada elemento da matriz à 5ª potência
np.power(arr9,5)

array([[100000, 100000],
       [100000, 100000]], dtype=int32)

# NumPy - matemática vetorial 

In [32]:
# Raiz quadrada de cada elemento da matriz
np.sqrt(arr9)

array([[3.16227766, 3.16227766],
       [3.16227766, 3.16227766]])

In [33]:
# Seno de cada elemento na matriz
np.sin(arr9)

array([[-0.54402111, -0.54402111],
       [-0.54402111, -0.54402111]])

In [34]:
# Log natural de cada elemento da matriz
np.log(arr9)

array([[2.30258509, 2.30258509],
       [2.30258509, 2.30258509]])

In [35]:
# Valor absoluto de cada elemento da matriz
np.abs (arr9)

array([[10, 10],
       [10, 10]])

In [38]:
# Matriz de exemplo abaixo com todos valores 1.6
arr10 = np.full ((4,4),1.6)
# Arredonda para cima para o int mais próximo 2
np.ceil (arr10)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [39]:
# Arredonda para baixo para o int mais próximo
np.floor (arr10)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# Arredonda para o int mais próximo
np.round (arr10)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

# NumPy - estatística 

In [42]:
# Retorna a média ao longo de um eixo específico
np.mean (arr10,axis=0)

array([1.6, 1.6, 1.6, 1.6])

In [43]:
# Retorna a soma de arr10
arr10.sum()

25.6

In [44]:
# Retorna o mínimo valor de arr10
arr10.min()

1.6

In [46]:
# Retorna o valor máximo do eixo específico
arr10.max (axis=0)

array([1.6, 1.6, 1.6, 1.6])

In [47]:
# Retorna a variância da matriz
np.var (arr10)



0.0

In [48]:
# Retorna o desvio padrão do eixo específico
np.std (arr10,axis=1)

array([0., 0., 0., 0.])

In [54]:
# Retorna o coeficiente de correlação da matriz
np.corrcoef(arr10)

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])